version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql8-test
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
